class HarvestsController < ApplicationController
  def index
    @harvests = Harvest.joins(:partner).where('date >= ?', DateTime.now)
  end

  def number_needed
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
    puts "METHOD"
  end
end
